
server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/shopping?characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
  thymeleaf:
    mode:  HTML5

mybatis:
  mapper-locations: classpath*:com/neuedu/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql



business:
    imageHost: http://img.neuedu.com/


#图片上传的路径配置
upload:
  path: F:\\Neuedu\\upload\\



redis:
  maxTotal: 8
  maxIdle: 8
  minIdle: 0
  blockWhenExhausted: true
  maxWaitMillis: 10000
  testOnBorrow: true
  testOnReturn: true
  jmxEnabled: true
  redisHost: 39.107.236.192
  redisPort: 6379
  #redisPassword:
  timeout: 5000



ftp:
  host: 39.107.236.192
  user: ftpuser
  pass: 123456


alipay:
  callback:
    url: http://localhost:8888/order/alipay_callback.do
  public:
    key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAh9ybrkBMt9x8ndZH4MhTulT3wVZ/m1kxQuhiSpGkk42nzpwzDZeFTTSIsgFZ9HLrpMQR722WC6ec5PLujYj1cfJQNUpkAkdcLDiaT3Dv4cU+QvrDhJHJqP6blps+IoI6gsK5Ns2/0nZ/wmnva6QdLaUJDMJgP9pShQX6bxEFYGolC3ii8lfnMHwp6kqgx0ujZy8YWn1393KHPqeIiUpArykT6iKtLmhPdgu6qhyngHulq6ppBdc3NsEoSeotbpQb5UugPPz74r3+5k2fWibohv4ElxfMIg5taL8USMOhXL3u7yShCq1RpvhoA5q7bgELNJCz8PhlRw6JJ1MA+taoEQIDAQAB

